version: '3'

services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:7.0.8-alpine
    
